//---------------------------------------------------------------------------//
// Copyright (c) 2020 Mikhail Komarov <nemo@nil.foundation>
// Copyright (c) 2020 Nikita Kaskov <nbering@nil.foundation>
//
// Distributed under the Boost Software License, Version 1.0
// See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt
//---------------------------------------------------------------------------//

#ifndef ALGEBRA_MP_DEFINES_HPP
#define ALGEBRA_MP_DEFINES_HPP

#include <boost/multiprecision/number.hpp>
#include <boost/multiprecision/cpp_int.hpp>
#include <boost/multiprecision/cpp_modular.hpp>

BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(94)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(149)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(160)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(178)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(180)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(181)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(182)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(183)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(192)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(224)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(239)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(254)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(255)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(256)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(292)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(295)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(296)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(298)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(381)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(546)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(595)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(893)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(894)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(913)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(1024)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(1490)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(1536)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(2048)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(3072)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(4096)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(6144)
BOOST_MP_DEFINE_SIZED_CPP_INT_LITERAL(8192)

#endif    // ALGEBRA_MP_DEFINES_HPP
