name: Publish Crypto3 Test Results (Reusable)

on:
  workflow_call:

permissions: {}

jobs:
  publish-result:
    name: Publish Junit tests result
    runs-on: ubuntu-22.04
    permissions:
      checks: write

    steps:
      # - name: Download Artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     pattern: test-results-*
      #     path: test-results
      #     merge-multiple: true

      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: test-results-linux
          path: test-results-linux
        continue-on-error: true

      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: test-results-mac
          path: test-results-mac
        continue-on-error: true

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        with:
          files: "test-results-*/**/*.xml"
          comment_mode: ${{ github.event.pull_request.head.repo.fork && 'off' || 'always' }}
